phrase:
  access_token: df8940c0b735df75b23f33b93c47a9d53e204c897dcbc8dfc83f432031c51894
  project_id: 8e0000aef7ca2913c7ec8c2b35ad7dd9
  file_format: i18next

  push:
    sources:
    - file: ./feed/translator/master/translation.en.json
      params:
        locale_id: en
        tags: feed
        update_translations: true
    - file: ./nav-bar/translator/master/translation.en.json
      params:
        locale_id: en
        tags: nav-bar
        update_translations: true
    - file: ./select/packageFolder/translator/master/translation.en.json
      params:
        locale_id: en
        tags: select
        update_translations: true

  pull:
    targets:
    - file: ./<tag>/translator/master/translation.<locale_name>.json
      params:
        tags: feed, nav-bar
        file_format: simple_json
    - file: ./<tag>/packageFolder/translator/master/translation.<locale_name>.json
      params:
        tags: select
        file_format: i18next_4
