phrase:
  access_token: df8940c0b735df75b23f33b93c47a9d53e204c897dcbc8dfc83f432031c51894
  project_id: a1830f3dd54d6de4af698b7a52b8e77d
  push:
    sources:
    - file: ./translator/master/translation.en.json
      params:
        locale_id: en
        tags: select
        file_format: i18next
        update_translations: true
  pull:
    targets:
    - file: ./translator/master/translation.<locale_name>.json
      params:
        tags: select
        file_format: simple_json
