name: PhraseCliSetup

on:
  pull_request:
    branches: [ "main" ]
    paths: ['**/translation.en.json']

jobs:
  phraseCliSetup:
    name: Setup Phrase CLI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Phrase CLI install
      uses: phrase/setup-cli@v1
      with: 
        version: 2.6.6
        run: phrase push --wait --tag ${{ github.ref_name }}
